cli/gluster-block.c, rpc/block_svc_routines.c, rpc/glfs-operations.c, rpc/glfs-operations.h, rpc/rpcl/block.x, utils/capabilities.h, utils/common.c, utils/gluster-block-caps.info, utils/utils.h
Earlier these changes where tracked/reviewed at:
https://review.gluster.org/#/c/18787/
https://review.gluster.org/#/c/19665/
Please refer the links for complete context.
=> Resize support

rpc/block_svc_routines.c
Defaultly the block device will create one default alua tpg, but
this is buggy in some old kernel, so we need to create a new one
instead of using the default one.
Fixes: #48
Change-Id: I07ed7c084825336684050766532452964c00e94d
Many thanks for your interest in improving gluster-block!
gluster-block does not use GitHub Pull-Requests. Instead, changes are reviewed
on the Gerrit instance of the Gluster Community at https://review.gluster.org
In order to send your changes for review, follow these steps:
1. login on https://review.gluster.org with your GitHub account
2. add a public ssh-key to your profile on https://review.gluster.org/#/settings/ssh-keys
3. add the Gerrit remote to your locally cloned git repository
$ git remote add gerrit …
=> create: create glfstpg and set the alua type to None

docs/gluster-block.8
=> doc: man page update

cli/gluster-block.c, rpc/block_svc_routines.c, rpc/rpcl/block.x, utils/common.c, utils/common.h, utils/utils.h
```
$ gluster-block genconfig                                                        
Inadequate arguments for genconfig:                                              
gluster-block genconfig <volname[,volume2,volume3,...]> enable-tpg <host> [--json*]
$ gluster-block genconfig testvol1,testvol2 enable-tpg 192.168.124.227                      
{                                                                                
"storage_objects":[                                                            
{                                                                            
"alua_tpgs":[                                                              
{                                                                        
"alua_access_type":0, …
```
=> regenconfig: add support

daemon/gluster-blockd.c, rpc/block_svc_routines.c, rpc/glfs-operations.c, rpc/glfs-operations.h
* delete: add a way to saveconfig with delete operation
* modify: return fail if block is not loaded
=> Saveconfig fixes

rpc/block_svc_routines.c, utils/utils.h
Before:
[root@localhost gluster-block]# gluster-block delete sample/block
FAILED ON:   192.168.124.217
SUCCESSFUL ON:   192.168.124.6 192.168.124.163
RESULT: SUCCESS
After:
[root@localhost gluster-block]# gluster-block delete sample/block
FAILED ON:   192.168.124.217
SUCCESSFUL ON:   192.168.124.163 192.168.124.6
RESULT: FAIL
=> delete: fix glusterBlockDeleteRemoteAsync ret value

rpc/glfs-operations.c, utils/utils.h
Just like gluster file volume reserve 1% space, and Heketi reserves 2% space
currently. Reserving some space for block-meta within block hosting volume can
solve some potential issues.
Problem:
-------
Say, if the block hosting volume is 100% used, we expect the block volume delete
operation should free some space. But since the delete operation will also incur
some metadata writes into the respective block meta file, the meta writes will
fail with ENOSPC. Hence the block delete operation will be terminated.
Solution:
--------
On every create request we should do glfs_statvfs() on the block hosting volume,
```
if (($freeSize - $reserveSpace) >= reqBlockSize) {
---
proceed with the block create request
---
} else {
---
fail the block create request
---
}
```
How much reservation needs to …
=> meta: reserve 10M space for meta-data store

rpc/block_svc_routines.c, rpc/glfs-operations.c
=> resize: fix errCode overriding

rpc/block_svc_routines.c
if the PRIOPATH and old-node are the same then update PRIOPATH at metadata
with the new-node. Also defend the same at create activity as part of
replace node operation.
=> replace-node: update PRIOPATH at metadata when it match with old-node

rpc/block_svc_routines.c
Indentation is reduced by removing some else
branches (taking into account the "goto out"
in the if branch).
This improves the code flow, imho.
Best seen with "git show -w" which does not show
the indentation changes.
Signed-off-by: Michael Adam <obnox@samba.org>
Reviewed-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
Reviewed-by: Xiubo Li <xiubli@redhat.com>
=> audit: reduce indentation for smoother flow

rpc/block_svc_routines.c
=> Fix memleak for errMsg

cli/gluster-block.c, daemon/gluster-blockd.c, utils/common.c, utils/lru.c, utils/utils.c, utils/utils.h
Ensure:
On FAILURE dump error msg to stderr
On SUCCESS dump response to stdout
Fixes: #117
=> gluster-block: dump all failure msgs to stderr

daemon/gluster-blockd.c
change kernel version
from 3.10.0-862.11.1 (RHEL-7.5.3) to 3.10.0-862.14.4 (RHEL-7.5.4)
=> daemon: change minimum rhel kernel version to 3.10.0-862.14.4

README.md
=> README: update the multipath.conf detail for load-balance support

cli/gluster-block.c, rpc/block_svc_routines.c
=> gluster-blockd: defend for NULL to avoid crash

rpc/block_svc_routines.c, utils/capabilities.c, utils/utils.h
Fixes for coverity 'high' priority warnings as per https://scan.coverity.com/projects/gluster-block_a (Check view defects).
=> fix coverity high priority warnings

cli/gluster-block.c
This is basically what we have missed at #121
=> cli: push output to stderr if remote rpc return non-zero

configure.ac, rpc/Makefile.am, rpc/glfs-operations.c
=> version: add the gfapi version check

cli/gluster-block.c
=> logger: fix the log messages with adding extra whitspace

README.md
Simple 2 node setup demo:
* on server node:
- runs glusterd (glusterfs-server) and gluster-blockd daemon
- where we create a block hosting volume and then create a block volume on it
* on client node:
- runs iscsid daemon
- where we login to previously created block volume and perform some IO
=> README: add a simple demo

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> docs: add ISSUE and PR TEMPLATE

tests/basic.t
=> tests: use ip addr instead of hostname

configure.ac
Reduce the buidling redudant info.
=> automake: silent building

.gitignore, Makefile.am, configure.ac, tests/Makefile.am, tests/basic.t, tests/gfapi-test.c
=> tests: add simple gfapi access test

.travis.yml, extras/docker/Dockerfile.centos7, extras/docker/Dockerfile.fedora29
Add Travis builds for:
* Fedora 28
* Fedora 29
* Centos 7
=> travis: build on f27, f28, f29 and centos7

daemon/gluster-blockd.c, utils/utils.c, utils/utils.h, version.h
defend on minimum targetcli, tcmu-runner versions.
Fixes: #76
Fixes: #118
I hope, we are good with,
Requesites:
targetcli   >= 2.1.fb46
tcmu-runner >= 1.1.3
=> daemon: check for dependencies versions at runtime

README.md
=> readme: add libtirpc-devel rpcgen as perrequesites

tests/basic.t, tests/gfapi-test.c
Problem:
-------
Need to more test cases to do the code coverage.
Solution:
--------
Add more test cases that possiblly, such as for the 'create' add
'ha|prealloc|ring-buffer....', etc.
Fixes: #
=> tests/basic.t: add more test cases

rpc/block_svc_routines.c, rpc/glfs-operations.c
Fix the code style and some strange logs output.
such as it will be look like: 
"... block_volume/block_volume ..."
"... on volume (null) ..."
No issue about this.
=> modify: misc fix for the logs

INSTALL, README.md, docs/gluster-block.8
Problem:
-------
There are many new feature or fixing has been added, but forgot to
update the docs.
Resolution:
---------
Update them to the upstream latest.
=> Docs: update to the latest

rpc/glfs-operations.c
Problem:
-------
In case of block hosting volume types like EC/disperse,
glfs_zerofill is not supported, since prealloc is ON by default,
block volume creates will fail.
Solution:
--------
In case if glfs_zerofill() fails with ENOTSUP, perform a
slow write of zeros to the file.
Fixes: https://github.com/gluster/gluster-block/issues/149#issuecomment-484408869
Thanks to @inevity for reporting.
Thanks @nixpanic  and @lxbsz for your thoughts about the solution.
=> zero-fill: use slow zeroing if glfs_zerofill is not supported

INSTALL, README.md, docs/gluster-block.8, docs/gluster-blockd.8
- reorganize README
- updated INSTALL guide
- updated man pages
=> docs: update

MAINTAINERS.md
=> add MAINTAINERS.md file

INSTALL, README.md
- add glusterfs-server to the install list
- add MAINTAINER FILE details to the ReadME
- add community contact details to README
- defend multipath.conf based on tcmu-runner version
- add initiator side commands for resize block
This were the missing things I found on the pre-release testing
=> doc: update README

.github/ISSUE_TEMPLATE.md, NEWS, README.md, version.h
=> NEWS: update

rpc/block_svc_routines.c
Currently we are only using the ALUA's Primary Target Port Group
with implicit transition, which will only use the active/optimized
and active/non-optimized states, so all the others should be disabled
here. Or it will report the wrong state to initiator like:
Report target port groups:
target port group id : 0x2 , Pref=0
target port group asymmetric access state : 0x01
T_SUP : 1, O_SUP : 1, LBD_SUP : 0, U_SUP : 1, S_SUP : 1, AN_SUP : 1, AO_SUP : 1
...
target port group id : 0x1 , Pref=0
target port group asymmetric access state : 0x00
T_SUP : 1, O_SUP : 1, LBD_SUP : 0, U_SUP : 1, S_SUP : 1, AN_SUP : 1, AO_SUP : 1
...
=> alua: disable the usless ALUA state

README.md, cli/gluster-block.c, daemon/gluster-blockd.c, docs/gluster-block.8, rpc/block_svc_routines.c, rpc/glfs-operations.c, rpc/glfs-operations.h, rpc/rpcl/block.x, tests/basic.t, utils/capabilities.c, utils/capabilities.h, utils/common.c, utils/common.h, utils/gluster-block-caps.info, utils/utils.c, utils/utils.h, version.h
Add hw block size setting support and this still will depend on the taregetcli's saveconfig support.
BZ#1710833
=> blksize: add hw block size setting support

extras/upgrade_activities.sh
When the upgrade activities script finishes and exit successfully,
the gluster-blockd daemon running in the background may still not
killed, so this will be a problem when the gluster-block service
try to start:
ERROR: gluster-blockd is already running...
And also when running the gluster-blockd daemon in background it
may need a while to get fired, so here will always try 5 times by
waiting 1 second each time.
=> upgrade_activities: always wait till the background daemon is terminated

cli/gluster-block.c, docs/gluster-block.8, rpc/block_svc_routines.c, utils/common.h
Previously we had code which allows passing more than HA number of hosts to the
create command. But the future was incomplete and this code was left dead.
This PR removes it all, may be once we have self-healing, this sort of  feature
addition becomes more easy.
This removes a lot of complexity at server side create code, both in terms of readability and back and forth within the code.
=> cleanup: remove unsupported code

rpc/block_create.c, rpc/block_delete.c, rpc/block_genconfig.c, rpc/block_info.c, rpc/block_list.c, rpc/block_modify.c, rpc/block_replace.c
This will fix the issue when the create/delete are actually failed
but the logs will still say create/delete cli return success.
=> create/delete: fix the return check logs

tests/gfapi-test.c
Fix error handling in the gfapi test
=> tests: fix error handling in gfapi test

version.h
$ gluster-blockd
[...]
Parameter loglevel_file is now 'info'.
Parameter max_backup_files is now '100'.
[...]
Parameter auto_save_on_exit is now 'false'.
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: cannot import name version
=> gluster-blockd: fix import error

rpc/block_replace.c
Previously:
Always no authentication set on new node
Fix:
Makesure to update authentication details on the new node
=> replace: fix authentication on the new-node

ansible/roles/servers/tasks/install.yml
targetcli is hanging with
* https://github.com/open-iscsi/targetcli-fb/pull/156
This is fixed now with
* https://github.com/open-iscsi/targetcli-fb/pull/165
=> Vagrant: remove patch reverting in targetcli

cli/gluster-block.c, rpc/block_create.c
If the configshell version is low, even we do not specify the
io-timeout options, it will fail, but the exepcting should just
skip it.
Fixes: #
=> create: fix failing with io_timeout not support

daemon/gluster-blockd.c, utils/capabilities.c, utils/utils.c, utils/utils.h, version.h
If the version is not provided by the package itself, check if the rpm nvr has the version string that can be used.
=> version: fall back to rpm package nvr if needed

rpc/block_modify.c
Problem:
-------
If modify size fails on one node, after fixing the issue a retry with
should fix the configuration on previously failed node. But retrying modify size
is bailing out.
This is a side effect caused with our recent changes made with
'resize: update the size in metafile soon after ResizeEntry'
$ gluster-block modify sample/block1 size 2MiB
IQN: iqn.2016-12.org.gluster-block:02268663-117e-4c19-a9df-e11a5ba42715
FAILED ON:  192.168.124.172
SUCCESSFUL ON:  192.168.124.121 192.168.124.40
RESULT: FAIL
After fixing 192.168.124.172, retrying modify gives below
error:
$ gluster-block modify sample/block1 size 2MiB
request size (2.0 MiB) is same as current size (2.0 MiB) ]
RESULT:FAIL
=> resize: retry doesn't care about all nodes status

rpc/block_common.h, rpc/block_info.c, rpc/block_modify.c, rpc/block_svc_routines.c, rpc/glfs-operations.c, rpc/glfs-operations.h
```
$ gluster-block modify blockhostingvol/blockvol size 4GiB --json-pretty
{
"IQN":"iqn.2016-12.org.gluster-block:7a4938b1-f153-4de7-b91a-04c34fb57f36",
"FAILED ON":[
"192.168.121.55",
"192.168.121.206"
],
"SUCCESSFUL ON":[
"192.168.121.253"
],
"RESULT":"FAIL"
}
$ gluster-block info blockhostingvol/blockvol
NAME: blockvol
VOLUME: blockhostingvol
GBID: 7a4938b1-f153-4de7-b91a-04c34fb57f36
SIZE: 4.0 GiB
HA: 3
IOTIMEOUT: 0 Seconds
PASSWORD:
EXPORTED ON: 192.168.121.253 192.168.121.55 192.168.121.206
RESIZE FAILED ON: 192.168.121.55:[2.0 GiB] 192.168.121.206:[1.0 GiB]
$ gluster-block info blockhostingvol/blockvol --json-pretty
{
"NAME":"blockvol",
"VOLUME":"blockhostingvol",
"GBID":"7a4938b1-f153-4de7-b91a-04c34fb57f36",
"SIZE":"4.0 GiB",
"HA":3,
"IOTIMEOUT":"0 Seconds",
"PASSWORD":"", …
```
=> info-cmd: add list of resize failed nodes

daemon/gluster-blockd.c, rpc/block_create.c
latest targetcli daemon approach set interactive mode as default to make it
appear similar to cli approach, hence to use previous batch mode we need
some global settings.
Depends on: targetcli#pull/167
=> daemon: switch to batch mode when available

daemon/gluster-blockd.c, utils/utils.c, version.h
align GLUSTER_BLOCK_VERSION to PACKAGE_VERSION
=> version: fix GLUSTER_BLOCK_VERSION

rpc/glfs-operations.c
To defend a rare case like when the gluster bricks goes down/up
randomly, there is a chance that, unlink of backend file return success
but the writev to metadata file about 'ENTRYDELETE: SUCCESS' failed.
In such cases this patch allow delete to progress.
Fixes: BZ#1847425
=> delete: allow when backend file is absent
