gluster/gluster-block

- cli/gluster-block.c
- rpc/block_svc_routines.c
- rpc/glfs-operations.c
- rpc/glfs-operations.h
- rpc/rpcl/block.x
- utils/capabilities.h
- utils/common.c
- utils/common.h
- utils/gluster-block-caps.info
- utils/utils.h
$ gluster-block --help
[...]
commands:
create  <volname/blockname> [ha <count>]
[auth <enable|disable>]
[prealloc <full|no>]
[storage <filename>]
[ring-buffer <size-in-MB-units>]
<host1[,host2,...]> <size>
create block device [defaults: ha 1, auth disable, prealloc no, size in bytes,
ring-buffer default size dependends on kernel]
[...]
$ gluster-block create dht0/block33 ring-buffer 60 ha 3 192.168.195.137,192.168.195.134,192.168.195.135 1G --json-pretty
{
"IQN":"iqn.2016-12.org.gluster-block:1e9d26a4-28d7-43a5-a2dc-b7d08a6cbedd",
"PORTAL(S)":[
"192.168.195.137:3260",
"192.168.195.134:3260",
"192.168.195.135:3260"
],
"RESULT":"SUCCESS"
}
$ cat block-meta/block32
VOLUME: dht0
GBID: da787d30-ac8a-420c-8907-09b494e07ebf
HA: 3
ENTRYCREATE: INPROGRESS
SIZE: 1073741824
RINGBUFFER: 60 …
> create: add TCMU Ring Buffer size settable

- rpc/block_svc_routines.c
- rpc/glfs-operations.c
warning: suggest parentheses around assignment used as truth value [-Wparentheses]
warning: unused variable 'i' [-Wunused-variable]
> fix compiler warnings

- cli/gluster-block.c
- utils/common.c
For the not aligned target device size there is no specific use case.
And the unaligned size will make the code more complicated and useless,
because the LIO backend file will try to round down the size to
GB_DEFAULT_SECTOR_SIZE by default.
> gluster-block: align the target device size to GB_DEFAULT_SECTOR_SIZE

- rpc/block_svc_routines.c
0 means the fired or pending SCSI commands will wait forever, and
when the IOs going on and tcmu-runner process is crashed, so the
iscsi_ttx process will stucked forever.
Fixes: bz#1596684
> gluster-block: set the cmd_time_out to 130

- rpc/block_svc_routines.c
For the last commit just forget the genconf.
Setting cmd_time_out to 0 means that the iscsi_trx will wait
infinite until the cmds fired to tcmu-runner return back. Just
in case if tcmu-runner is killed/terminated, the iscsi_trx will
hung in D state infinitely, which later result in KERNEL WARNING
messages, like:
(2018-07-02 2:44:41 PM) xiubli_2: Jul 02 04:38:34 rhel1 kernel: Call Trace:
(2018-07-02 2:44:43 PM) xiubli_2: Jul 02 04:38:34 rhel1 kernel: iscsi_ttx D ffff9a69b6a64100 0 3413 2 0x00000084
[...]
The defaults,
GLUSTER ping timeout = 42
/etc/iscsi/iscsi.conf:node.session.timeo.replacement_timeout = 120
so cmd_time_out should be
cmd_time_out > GLUSTER ping timeout && cmd_time_out > replacement_timeout
The hack is to make cmd_time_out expire after
fast_io_fail_tmo/replacement_timeout. …
> gluster-block: set the cmd_time_out to 130 for genconf

- extras/wait-for-bricks.sh
- tests/glusterfs/wait-for-bricks-test.sh
Problem:
When a node is rebooted, by the time tcmu-runner starts there is no
guarantee that the bricks of the volume on which the block-volumes
are created will be online. This leads to a case where doing open
on the block files leads to open failing with ENOTCONN leading
to containers with this as pvc are in failed state.
Fix:
A script is added which will be added as a unit file dependency for
gluster-blockd which makes sure that the bricks are online for the
block-hosting-volume preventing this situation.
> Script to wait for bricks to come online

- Makefile.am
- configure.ac
- extras/Makefile.am
- gluster-block.spec.in
- systemd/gluster-block-target.service.in
- systemd/gluster-blockd.service.in
- utils/Makefile.am
This patch:
* install wait-for-bricks.sh (source install and rpm install)
* change install path of gluster-block-caps.info
depends on #98
> gluster-block: install wait-for-bricks.sh

- extras/wait-for-bricks.sh
1) 'pidof' command may not exist in all setups, so changing that
to use 'ps' command which is available more often. If 'ps' command is
not found in the setup it prints that the command is not available
in the setup in the error log.
2) For finding if 10 block volumes are up and running it was taking 9 seconds
when all the bricks are up. I changed the script to reduce the number of
gluster commands that are executed to get this time to 1 seconds.
Signed-off-by: Pranith Kumar K <pkarampu@redhat.com>
> wait-for-bricks: Use ps instead of pidof, improve performance

- rpc/block_svc_routines.c
ERROR: target iqn creation failed for: sample/block1 [at block_svc_routines.c+3959 :<blockValidateCommandOutput>]
INFO: command exit code, -1 [at block_svc_routines.c+4366 :<block_create_common>]
The string will be "Created target iqn.2016-12.org.gluster-block::34c5d642-338a-4782-b595-f0dfc33d5c34."
This was introuduced by commit 0722750be4b1f064.
> create: fix iscsi iqn validation check error

- .gitignore
- daemon/gluster-blockd.c
- systemd/gluster-blockd.sysconfig
- utils/Makefile.am
- utils/dyn-config.c
- utils/lru.c
- utils/lru.h
- utils/utils.c
- utils/utils.h
Using this patch there is no need to restart the gluster-blockd
daemon after the /etc/sysconfig/gluster-blockd is changed.
Currently we only support the logging dynamic reloading, and the
others config parameters will be supported later.
System config for gluster-block, for now there are only 3 option types supported:
1, The "int type" option, for example:
gb_int = 2
2, The "string type" option, for example:
gb_str = "Tom"  --> Tom
or
gb_str = 'Tom'  --> Tom
or
gb_str = 'Tom is a "boy"' ---> Tom is a "boy"
or
gb_str = "'T' is short for Tom" --> 'T' is short for Tom
3, The "boolean type" option, for example:
gb_bool
Fixes: #61
> logging: add config dynamic reloading support

- daemon/gluster-blockd.c
Do not start gluster-block daemon if the current kernel version doesn't
meet the recommendation.
> daemon: defend on minimum recommended kernel version

- systemd/gluster-block-target.service.in
> systemd: clear the target config only when tcmu-runner is running

- .travis.yml
- Dockerfile.buildtest
This uses docker in travis-ci to test the build of gluster-block.
Fixes #114.
It is a possible substitute for PR #135 and possibly a quicker alternative for https://github.com/gluster/centosci/pull/28 .
This currently only tests the build and not the test for two reasons:
* The build.t script assumes gluster-block is installed as RPM (==> should probably change or create a second flavor)
* The tests have some requirements on the kernel, so difficult to do in container...
> Add travis-integration for build verification using docker

- gluster-block.spec.in
RPM build errors:
bogus date in %changelog: Tue Jun 22 2017 Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
The change fixes the above warning!
Fixes: #138
Signed-off-by: Amar Tumballi <amarts@redhat.com>
> spec-file: fix the error in changelog date

- utils/common.c
- utils/utils.c
For global structure initialization, set only the fields
which are non-zero.
Fixes: #140
Signed-off-by: Amar Tumballi <amarts@redhat.com>
Reviewed-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
Reviewed-by: Xiubo Li <xiubli@redhat.com>
> all: fix build warnings

- utils/dyn-config.c
> dyn-config: read the config file line by line instead of allocating a fixed 32K buffer

- rpc/block_svc_routines.c
Ignore the vim temporary recovery files .%.sw*
Fixes: #151
> list: ignore the vim temporary recovery files

- rpc/block_svc_routines.c
- rpc/glfs-operations.c
[...]
genconfig <volname[,volume2,volume3,...]> [enable-tpg <host>|load-balance]
generate the block volumes target configuration.
[...]
The load-balance option will create the prio.info meta file and
set the prio path for each block created from old version automatically.
Fixes: #134
> genconfig: add load-balance support

- daemon/gluster-blockd.c
- rpc/block_svc_routines.c
- rpc/glfs-operations.c
- systemd/gluster-blockd.sysconfig
- utils/utils.c
- utils/utils.h
What is it ?
---
This patch is majorly for GCS and kube use-case, where the discovery service,
whos name look like FQDN will resolve the backend volfile servers path, for
each and every block hosting volume from all the associated pods/nodes in the
cluster.
As of today gluster-blockd and tcmu-runner use localhost as volfile server
address to communicate with block hosting volumes, with this patch series we
will provide a way to set volfile server address (discovery service) of a
remote/separate gluster cluster, where the block hosting volume is running out-
side the gluster-block (daemon running) nodes.
This way, we achieve the isolation between the glusterd and gluster-blockd
daemons, and hence they both can now run in different nodes/pods.
How to use:
---
Just uncommnet below line at …
> gluster-blockd: support volfile server (discovery service) setting through Env

- utils/utils.h
LOG() macro was designed to compare for specific strings, and based
on the result, log to different log files. This was done using
'strcmp()', but was using static strings. It made sense to compare
the static string directly as they resolve to same pointer while
compiling.
With this fix, was able to resolve 58 coverity issues in one shot.
Signed-off-by: Amar Tumballi <amarts@redhat.com>
> coverity: fix pointless_string_compare issues

- cli/gluster-block.c
- rpc/block_svc_routines.c
- utils/dyn-config.c
Some coverity IDs are:
326396 - Constant variable guards deadcode
326345 - Argument cannot be negative
326355 - Infinite loop
326371 - Printf format string issue
328498 - Resource leak
328500 - Unchecked return value
326360 - Explicit null dereference
Signed-off-by: Amar Tumballi <amarts@redhat.com>
> coverity: fix multiple issues

- cli/gluster-block.c
- daemon/gluster-blockd.c
- rpc/rpcl/Makefile.am
- systemd/gluster-blockd.sysconfig
- utils/Makefile.am
- utils/common.h
- utils/dyn-config.c
- utils/utils.c
- utils/utils.h
There are two rpc calls involved in the design,
Channel A: From cli process to local daemon (cli thread)
Channel B: From local daemon (cli thread) to remote daemon (remote thread)
Timeout for channel A is configurable now, using
/etc/sysconfig/gluster-blockd, by adjusting option 'GB_CLI_TIMEOUT' (in seconds)
$ cat /etc/sysconfig/gluster-blockd
GB_CLI_TIMEOUT=900
Changes to this value takes effect every time we start running/triggering new
cli command/request.
At the moment making Timeout configurable for channel B is not important, it is
hardcoded as 300 seconds in the code for now.                                  
Some more details:
-----------------
It would have been an easy fix calling clnt_control() right after clnt_create(),
unfortunately there is a bug in glibc, which is why we …
> cli-timeout: make rpc-timeout as configurable option

- cli/gluster-block.c
- rpc/glfs-operations.c
* cli: do not allow 'ha 0'
How to test:
$ gluster-block create sample/block ha 0 192.168.43.158 1MiB
* blockGetPrioPath: avoid crash when nhosts is zero
How to test:
$ touch /mnt/block-meta/block
$ gluster-block genconfig sample enable-tpg 192.168.43.158
> Minor fixes

- cli/gluster-block.c
- utils/utils.h
gluster-block (0.3)
usage:
gluster-block [timeout <seconds>] <command> <volname[/blockname]> [<args>] [--json*]
commands:
[...]
common cli options: (fixed formats)
timeout <seconds>
it is the time in seconds that cli can wait for daemon to respond.
[default: timeout 300]
--json*
used to request the output result in json format [default: plain text]
supported JSON formats: --json|--json-plain|--json-spaced|--json-pretty
Precedence of various methods to set cli timeout:
1. Options set through config file /etc/sysconfig/gluster-blockd          [Top Prio]
eg: uncommenting and adjusting key:value at /etc/sysconfig/gluster-blockd
2. Argument passed at cli
eg: timeout 900
3. Environment variable
eg: export GB_CLI_TIMEOUT=900
4. Code level defaults (300 sec) …
> cli: add timeout option

- systemd/gluster-blockd.service.in
In some test case we hit that the gluster-blockd service failed
due to the rpcbind service is not up.
> service: update the required rpcbind service start sequence

- rpc/block_svc_routines.c
- utils/dyn-config.c
- utils/utils.c
- utils/utils.h
passing the strlen() of the source string as the destination
length is pointless, and gcc-8 now warns about it:
utils.c: In function ‘gbStrcpy’:
utils.c:432:11: warning: ‘strncpy’ specified bound depends on the
length of the source argument [-Wstringop-overflow=]
ret = strncpy(dest, src, n);
^~~~~~~~~~~~~~~~~~~~~
utils.c:427:16: note: length computed here
size_t n = strlen(src);
^~~~~~~~~~~
block_svc_routines.c:184:7: warning: ‘strncat’ specified bound 1
equals source length [-Wstringop-overflow=]
strncat(out, " ", 1);
^~~~~~~~~~~~~~~~~~~~
block_svc_routines.c:183:7: warning: ‘strncat’ specified bound
depends on the length of the source argument [-Wstringop-overflow=]
strncat(out, element, strlen(element));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> utils: fix compile warning

- README.md
- cli/gluster-block.c
As of now prealloc is off by default.
This patch change the default prealloc to full.
Fixes: #149
> create: turn 'prealloc full' by default

- README.md
- cli/gluster-block.c
- configure.ac
- daemon/gluster-blockd.c
- docs/gluster-blockd.8
- extras/Makefile.am
- extras/gluster-block.logrotate
- gluster-block.spec.in
- systemd/gluster-blockd.sysconfig
- utils/dyn-config.c
- utils/lru.c
- utils/utils.c
- utils/utils.h
> gluster-block: add logrotate support

- cli/gluster-block.c
reported by scan-build:
```
gluster-block.c:158:11: warning: Dereference of undefined pointer value
create_obj->block_hosts);
^~~~~~~~~~~~~~~~~~~~~~~
../utils/utils.h:176:23: note: expanded from macro 'LOG'
__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__);  \
^~~~~~~~~~~
1 warning generated.
```
> cli: fix dereference of undefined pointer value

- cli/gluster-block.c
- daemon/gluster-blockd.c
- utils/dyn-config.c
- utils/lru.c
- utils/utils.c
- utils/utils.h
Problem:
-------
Currently cli process Loads Config on every operation in cli process
context. Hence log msgs:
DEBUG: logLevel now is TRACE [at utils.c+50:<glusterBlockSetLogLevel>]
DEBUG: glfsLruCount now is 5 [at lru.c+43:<glusterBlockSetLruCount>]
are dumped to gluster-blockd.log on every single cli operation. Apart
from the inotify triggers to Load Config.
Few Logs:
```
[2019-04-04 11:30:28.219482] CRIT: logLevel now is INFO [at utils.c+48 :<glusterBlockSetLogLevel>]                    
[2019-04-04 11:30:28.219572] CRIT: glfsLruCount now is 6 [at lru.c+42 :<glusterBlockSetLruCount>]                     
[2019-04-04 11:30:28.256593] INFO: event->mask: 0x2 [at dyn-config.c+519 :<glusterBlockDynConfigStart>]               
[2019-04-04 11:30:42.313931] CRIT: logLevel now is INFO [at …
```
> gluster-block: dump config key:value changes to respective log files

- cli/gluster-block.c
- utils/dyn-config.c
- utils/lru.c
* LoadConfig: don't call glusterBlockSetLruCount in cli process context
Because, we don't use LruCount in CLI context.
* cli: add log-msg for cli-timeout in DEBUG or higher level
gluster-block-cli.log:
[...]
[2019-04-05 08:20:38.738329] DEBUG: logLevel now is DEBUG [at utils.c+50 :\<glusterBlockSetLogLevel\>]
[2019-04-05 08:20:38.738515] DEBUG: cli timeout now is 300 [at gluster-block.c+171 :\<glusterBlockCliRPC_1\>] 
Log improvements.
> Log improve

- cli/Makefile.am
- cli/gluster-block.c
- configure.ac
- daemon/Makefile.am
- daemon/gluster-blockd.c
- gluster-block.spec.in
- rpc/Makefile.am
- rpc/rpcl/Makefile.am
- utils/Makefile.am
PR works with glibc sunrpc protocol:
$ ./autogen.sh && ./configure --enable-tirpc=no && make -j install
For using tirpc protocol:
$ ./autogen.sh && ./configure --enable-tirpc=yes && make -j install
or
$ ./autogen.sh && ./configure && make -j install
> Migrate to tirpc usage [Tested | Works on F27, F28, F29, Centos7]

- rpc/block_svc_routines.c
* fix leak reported by asan
```
==5943==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 17276 byte(s) in 18 object(s) allocated from:
#0 0x7fe4b07cfe60 in strdup (/lib64/libasan.so.5+0x3be60)
#1 0x497f5a in gbStrdup /root/gluster-block/utils/utils.c:461
#2 0x413858 in glusterBlockCallRPC_1 /root/gluster-block/rpc/block_svc_routines.c:615
#3 0x4180d6 in glusterBlockCreateRemote /root/gluster-block/rpc/block_svc_routines.c:960
#4 0x7fe4b076858d in start_thread (/lib64/libpthread.so.0+0x858d)
Direct leak of 396 byte(s) in 18 object(s) allocated from:
#0 0x7fe4b0883c08 in __interceptor_malloc (/lib64/libasan.so.5+0xefc08)
#1 0x7fe4b04478c7 in _IO_vasprintf (/lib64/libc.so.6+0x7a8c7)
Direct leak of 32 byte(s) in 2 object(s) allocated from:
#0 0x7fe4b0883c08 in __interceptor_malloc …
```
> Asan fixes

- cli/gluster-block.c
- daemon/gluster-blockd.c
- rpc/block_svc_routines.c
- utils/common.c
- utils/lru.c
- utils/utils.c
- utils/utils.h
Allow call the logger helpers without any variable argument
If there is no any variable argument in the logger helpers, it
will hit the following compile errors:
../utils/utils.h:175:34: error: expected expression before ‘,’ token
__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__);  \
^
gluster-blockd.c:268:5: note: in expansion of macro ‘LOG’
LOG ("mgmt", GB_LOG_ERROR, "Test................");
^
More detail please see the GNU doc:
https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html
No.
> logger: allow without any variable argument

- cli/gluster-block.c
- daemon/gluster-blockd.c
- rpc/block_svc_routines.c
- utils/common.c
- utils/lru.c
- utils/utils.c
- utils/utils.h
Allow call the logger helpers without any variable argument
If there is no any variable argument in the logger helpers, it
will hit the following compile errors:
../utils/utils.h:175:34: error: expected expression before ‘,’ token
__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__);  \
^
gluster-blockd.c:268:5: note: in expansion of macro ‘LOG’
LOG ("mgmt", GB_LOG_ERROR, "Test................");
^
More detail please see the GNU doc:
https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html
No.
> logger: allow without any variable argument [new]

- configure.ac
Fix Warning logs:
[root@Fedora-Server gluster-block]# ./configure --enable-tirpc=no
configure: WARNING: unrecognized options: --enable-tirpc
checking whether make supports nested variables... yes
[...]
configure: WARNING: unrecognized options: --enable-tirpc
\------------------ Summary ------------------
gluster-block version 0.3
Prefix.........: /usr/local
C Compiler.....: gcc -g -O2
Linker.........: /usr/bin/ld -m elf_x86_64
Using Tirpc....: no
\---------------------------------------------
Fixes: #212
> configure: fix warning about '--enable-tirpc'

- utils/utils.c
Warning seen with make:
\--------------------------------
```
$ make
[...]
In file included from utils.c:15:
utils.c: In function ‘glusterBlockSetLogLevel’:
utils.h:113:27: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-de
claration]
int __ret=asprintf(ptr, ##fmt);__ret;})
^~~~~~~~
utils.h:131:19: note: in expansion of macro ‘GB_ASPRINTF’
len = GB_ASPRINTF(&buf, fmt, ##__VA_ARGS__);             \
^~~~~~~~~~~
utils.c:41:5: note: in expansion of macro ‘MSG’
MSG(stderr, "unknown LOG-LEVEL: '%d'", logLevel);
^~~
CC       libgb_la-lru.lo
[...]
```
Compile time warnings.
> build: fix compile time warning

- gluster-block.spec.in
- version.h
Problem:
-------
TEST : gluster-block delete hosting-volume/block-volume
FAILED ON:   192.168.124.147
SUCCESSFUL ON: None
RESULT: FAIL
line 98 : NOT OK
Solution:
--------
This is because, the below command was failing,
$ targetcli /backstores/user:glfs delete name=block-volume save=True
Unexpected keyword parameter 'save'.
Since, gluster-block now use per storage object save feature of targetcli,
need, below commit from targetcli, to fix delete failures:
```
commit bca03ea400a691e4218113b6d10adb61ce0cd511 (refs/remotes/origin/save_del)
Author: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
Date:   Fri Jun 1 16:15:22 2018 +0530
saveconfig: way for block-level save with delete comman
```
which is part of targetcli-2.1.fb49, hence turning the dependency check to
latest released and …
> gluster-block: fix block delete failure

- rpc/block_svc_routines.c
Problem:
-------
TEST : gluster-block create hosting-volume/block-volume ring-buffer 32 192.168.124.184 1MiB
failed to configure on 192.168.124.184 configure failed
RESULT:FAIL
line 125 : NOT OK
Solution:
--------
We found out that the cfgstring containing commas is parsed correctly by
configshell and passed to the kernel without problems.
we used the following cfgstring:
'dev_config=glfs/hosting-volume@192.168.124.184/block-store/ed9ffb77-63b7-4a91-b2cd-f176eb5be847,max_data_area_mb=32'
But then we see that the ",key1=val1" part has been truncated by the kernel
Read More: https://bugzilla.redhat.com/show_bug.cgi?id=1623925#c24
Later, there was a new way to pass such options via targetcli , with:
```
commit ffafd9680228ec5c39cc721f0db50b7babc2c91d (refs/remotes/origin/control_str, …
```
> gluster-block: fix create failure with ring-buffer option

- daemon/gluster-blockd.c
$ targetcli get global max_backup_files
max_backup_files=10000
> config-backup: increase max backup files count

- Makefile.am
- cli/gluster-block.c
- daemon/gluster-blockd.c
- extras/Makefile.am
- gluster-block.spec.in
- rpc/block_svc_routines.c
- utils/utils.h
Problems:
--------
$ make rpms
[...]
warning: bogus date in %changelog: Sun Apr 3 2019
error: %changelog not in descending chronological order
make: *** [rpms] Error 1
Solution:
--------
Correct the date in the changelog and update the date to when the
PR is merged.
Problem:
-------
In RHEL, when the version is <= 7 or fedora <= 27, the libtirpc
library is provided by glibc, so the make rpms will failed when
doing the configure.
Resolution:
---------
Disable the libtirpc check in RHEL <= 7 or fedora <= 27 as default.
> Spec: misc fix

- cli/gluster-block.c
- daemon/gluster-blockd.c
- rpc/block_svc_routines.c
- rpc/glfs-operations.c
- utils/dyn-config.c
- utils/lru.c
- utils/utils.c
- utils/utils.h
Since we have make the cli and server routines into 2 different
processes in gluster-blockd daemon, the gbConf data will also
be have different copies. If the gbConf data is changed by the
dyn-config thread in the cli(parent) process, the new changes won't
be visible for the server(child) process.
Resolution:
----------
For the gbConf data, use the shared memory instead of the in the
data segment.
> gbConf: Use shared memory instead of from the data segment

- utils/lru.c
- utils/utils.c
Fix compile warnings:
```
utils.c: In function 'glusterBlockSetLogLevel':
utils.h:169:23: warning: 'level' may be used uninitialized in this function [-Wmaybe-uninitialized]
if (level <= gbConf->logLevel) {                           \
^
utils.c:96:7: note: 'level' was declared here
int level;
^
In file included from utils.c:19:0:
utils.h:369:21: warning: 'dom' may be used uninitialized in this function [-Wmaybe-uninitialized]
gbStrdup(&(dst), src,                                    \
^
utils.c:95:9: note: 'dom' was declared here
char *dom;
^
CC       libgb_la-lru.lo
lru.c: In function 'glusterBlockSetLruCount':
lru.c:70:5: warning: format '%d' expects argument of type 'int', but argument 5 has type 'size_t' [-Wformat=]
LOG("mgmt", GB_LOG_DEBUG,
^
```
> rpms: fix compile warnings

- configure.ac
- daemon/gluster-blockd.c
Systemd service will help to guarantee that the tcmu-runner is already up when reaching here.
To remove this in system case just want to avoid the gap in tcmu-runner and gluster-blockd services that
when the tcmu-runner service is dead, the gluster-blockd service won't exit in time and will be still active for a while, which will still to check the tcmu-runner daemon and exit by itself.
> daemon: remove the tcmu-runner active check in systemd case

- extras/gluster-block.logrotate
Problem:
---------
Normally we need to capture the SIGHUP in the gluster-blockd daemon,
but since we are fopening and creating the logfiles verytime in LOG(),
so there is no need to do the postrotate action.
Resolution:
------------
Remove the postrotate action in the logrotate config file.
> logrotate: remove postrotate action

- utils/utils.c
- utils/utils.h
Problem:
---------
Without this, all the logfiles will be initialized to NULL as, and
there will be the following errors with the log messages outputed
to stderr:
May 05 18:33:17 rhel3 gluster-blockd[18005]: Error opening log file: No such file or directory
May 05 18:33:17 rhel3 gluster-blockd[18005]: Logging to stderr.
Resolution:
-----------
Initialize the logfiles in initGbConfig together with the logDir.
> logger: init the logfiles in initGbConfig

- configure.ac
When doing set the --prefix=XXX the GLUSTER_BLOCKD_LIBEXECDIR will be:
GLUSTER_BLOCKD_LIBEXECDIR=NONE/libexec/gluster-block and when installing
it will be installed in extra/NONE/libexec/gluster-block/.
> configure.ac: set the libexecdir flexiblly depending on the prefix

- gluster-block.spec.in
rpmlint will ouput one warning like:
Warning:
gluster-block.x86_64: W: dangerous-command-in-%preun rm
Use the "find -delete" instead of "rm -rf"
> spec: fix rpmlint dangerous-command-in-%preun rm warning

- rpc/block_svc_routines.c
- utils/utils.h
create: split the creation into 2 phases
This will fix the following issues:
1, When the StorageObject creation failed the iqn will still be
created and won't be deleted in case of:
When creating BV with the same NAME, the second time it will fail
due to the targetcli cache db only allows one [user/$NAME] exist,
but will leave the iqn not deleted correctly.
That means there will be two different Targets will both mapped
to the same StorageObject.
2, For the case above we will also find that after the second
creation failing the /etc/target/saveconfig.json will be one
StorageObject with the second Target in pairs and exist.
In theory, there should be one StorageObject with 2 Targets.
This patch will split the creation into 2 phases: CREATE_SO_SRV
and CREATE_TG_SRV, since in the targetcli …
> create: fails directly when the StorageObject is already exist with the same NAME

- rpc/block_create.c
- rpc/glfs-operations.c
- tests/gfapi-test.c
- utils/lru.c
- utils/utils.c
Coverity issues reported at:
https://scan.coverity.com/projects/gluster-gluster-block?tab=overview
https://scan4.coverity.com/reports.htm#v43089/p15784
* Null pointer dereferences
* thread dead lock
* Error handling
> fix covery issues reported on 0.5dev (master)

- cli/gluster-block.c
- docs/gluster-block.8
The ringbuffer size for each target could up to the global limitation
which is 2GB, here we will allow it up to 1GB. This relevant kernel
patch has been updated into the same verions with the dynamic growth
and shrink patch set.
No.
> ringbuffer: fix the max limited size to 1024M

- rpc/block_genconfig.c
block_genconfig.c: In function 'block_gen_config_cli_1_svc':
block_genconfig.c:66:43: warning: '%s' directive output may be truncated writing up to 255 bytes into a region of size 239 [-Wformat-truncation=]
66 |   snprintf(lun_so, 256, "/backstores/user/%s", block);
|                                           ^~
In file included from /usr/include/stdio.h:867,
from ../utils/utils.h:16,
from ../utils/common.h:15,
from block_common.h:16,
from block_genconfig.c:12:
/usr/include/bits/stdio2.h:67:10: note: '__builtin___snprintf_chk' output between 18 and 273 bytes into a destination of size 256
67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68 |        __bos (__s), __fmt, __va_arg_pack ());
| …
> genconfig: fix one compile warning

- README.md
- cli/gluster-block.c
- daemon/gluster-blockd.c
- docs/gluster-block.8
- rpc/block_common.h
- rpc/block_create.c
- rpc/block_genconfig.c
- rpc/block_info.c
- rpc/block_replace.c
- rpc/block_version.c
- rpc/glfs-operations.c
- rpc/glfs-operations.h
- rpc/rpcl/block.x
- tests/basic.t
- utils/capabilities.c
- utils/capabilities.h
- utils/gluster-block-caps.info
- utils/utils.c
- utils/utils.h
- version.h
Set the tcmur_cmd_time_out=43s as default, which is larger than each IO's
timeout value(default is 30s) in the client/initiator side, and
at the same time it will be larger than 42s, the Gluster ping
timeout.
No
This depends on the following two PRs:
[1] https://github.com/open-iscsi/configshell-fb/pull/47
[2] https://github.com/open-iscsi/tcmu-runner/pull/568
> create: add tcmur_cmd_time_out option support

- cli/gluster-block.c
- rpc/rpcl/block.x
If we specify more than 2 volumes in one genconfig command line,
the genconfig will truncate the volumes.
Yeah
Fixes: #1787371
> genconfig: switch to string instead of fixed 255 for the volume

- rpc/block_info.c
- rpc/block_modify.c
On a resize operation, say the backend file expand succeed but the config
change on a remote node failed. In this case, the block hosting volume size
is already occupied. Hence the block volume info should return the currently
consumed size.
Needed-by: https://github.com/heketi/heketi/pull/1702
> resize: update the size in metafile soon after ResizeEntry

- Vagrantfile
vagrant-libvirt supports using QEMU user sessions to maintain Vagrant
VMs, and some distros turn it ON by default.
After upgrading to Fedora32 I have noticed `vagrant up` fails with a huge call
trace and disabling QEMU session worked.
More read:
https://github.com/vagrant-libvirt/vagrant-libvirt#qemu-session-support
https://fedoraproject.org/wiki/Changes/Vagrant_2.2_with_QEMU_Session
> vagrant: disable QEMU session support

- rpc/block_create.c
- rpc/block_info.c
- rpc/block_modify.c
- utils/utils.c
- utils/utils.h
An information-disclosure flaw was found in the way gluster-block logs
sensitive information. This flaw allows an attacker with access to the
gluster-block logs to read potentially sensitive information, such as
the CHAP passwords for block volumes.
When tuned to debug log-level, gluster-block captutures the targetcli exec
commands output at gluster-blockd.log which might contain sensitive details.
Also block volume create/modify/info cli command outputs might contain
sensitive information, as part of the audit logging these outputs will be
captured at cmd_history.log and gluster-blockd.log 
Fixes: CVE-2020-10762
> CVE fixes master

- rpc/block_delete.c
On delete, say the block target config on all the nodes is successfully
deleted, but the backend file couldn't get unlink may due to BHV full space.
In this case the retry of delete fails repeatedly.
> delete: fix subsequent delete failures
